# Generated by Django 2.2.2 on 2019-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190606_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(),
        ),
    ]
