# Generated by Django 2.2.2 on 2019-06-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190606_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='Id',
        ),
    ]
