# Generated by Django 2.2.2 on 2019-06-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190606_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
