# Generated by Django 2.2.2 on 2019-06-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190606_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Id',
            new_name='id',
        ),
    ]
